import "./globals.css";

import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import NavBar from "@/components/layout/NavBar";

const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${nunito.variable} w-full antialiased`}>
                <NavBar />
                {children}
            </body>
        </html>
    );
}
